name: basebloc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.1.2
  intl: any
  json_annotation: ^4.8.1
  table_calendar: ^3.0.9

dev_dependencies:
  build_runner: ^2.3.2
  build_verify: any
  flutter_launcher_icons: any
  flutter_lints: ^2.0.0
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  freezed: any
  go_router_builder: ^2.3.3
  hive_generator: any
  injectable_generator: any
  json_serializable: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/logo/
    - assets/images/splash/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100

flutter_launcher_icons:
  android: "ic_launcher"
  image_path_android: "assets/images/logo/logo.png"
  ios: true
  image_path_ios: "assets/images/logo/logo_ios.png"
  remove_alpha_ios: true

flutter_native_splash:
  image: "assets/images/splash/logo_splash.png"
  background_image: "assets/images/splash/background_splash.jpeg"    